### ISSUE TITLE
no README

### ISSUE THREAD

**Issue by robcee** [mikeconley/taburdle#3]
Cool addon, but what do the colors mean, Mike? There's no documentation. How do I win?

Not Wordle, just my @firefox tabs:
🟪🟪🟪🟪🟪
🟪🟪🟪🟪🟪
🟪🟪🟩🟨🟨
🟨🟨🟨🟨🟨
🟨🟨🟩🟨🟨
🟩🟨🟩🟩🟩
🟩🟩
https://mzl.la/3sfOF1R

**Comment by mikeconley** [comment]
Thanks! Merged your patch. Much appreciated!
